# Generated by Django 4.0.4 on 2022-05-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurant_total_save'),
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='save_post',
        ),
        migrations.AddField(
            model_name='user',
            name='like_menu',
            field=models.ManyToManyField(blank=True, related_name='like_menu', to='restaurant.menuitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='save_menu',
            field=models.ManyToManyField(blank=True, related_name='save_menu', to='restaurant.menuitem'),
        ),
    ]
