# Generated by Django 4.0.4 on 2022-05-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(default=0)),
                ('total_like', models.IntegerField(default=0)),
                ('total_save', models.IntegerField(default=0)),
            ],
        ),
    ]
