# Generated by Django 4.0.4 on 2022-05-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='total_save',
        ),
    ]
