# Generated by Django 4.0.4 on 2022-05-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurant_total_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurants',
            field=models.ManyToManyField(related_name='restaurants', to='restaurant.restaurant'),
        ),
    ]
