# Generated by Django 4.0.4 on 2022-05-24 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_menuitem_restaurant_menuitem_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant.restaurant'),
        ),
    ]
